name: sandbox
version: 0.0.1
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Sandbox allows to execute the Dart script anywhere (even in the pub cache).
homepage: https://github.com/mezoni/sandbox
dependencies:
  path: any
dev_dependencies:
  test: any